PlanetarisLib = require ("PlanetarisLib")
require ("prototypes.concrete")
require ("prototypes.hazard-concrete")
require ("prototypes.item")
require ("prototypes.item-groups")
require ("prototypes.pipes")
require ("prototypes.recipe")
require ("prototypes.stone-path")
require ("prototypes.technology")
require ("prototypes.sprites")
require ("prototypes.wall")